#!/bin/env python3

import json

GRAPH_FILE='licomp_dwheeler/data/david-wheeler-licenses.json'

with open(GRAPH_FILE) as fp:
    graph_data = json.load(fp)


print('digraph depends {')
print('  node [shape=box]')
for lic,value in graph_data['licenses'].items():
    for allowed in value['allowed']:
        print(f'    \"{lic}\" -> \"{allowed}\"')
print('}')
